version: "3.8"
services:
  php74_csvreader_development:
    container_name: php74_csvreader_development
    build:
      context: .
      dockerfile: ./.docker/Dockerfile/PHP74_Dockerfile
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    init: true
    command: >
      bash -c '
        composer install;
        tail -f /dev/null;
      '
